server:
  port: 8080
  servlet:
    context-path: /series

spring:
  application:
    name: series-service
  config:
    import: "optional:configserver:http://localhost:8888"

  data:
    mongodb:
      port: 27017
      database: seriesFP

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
